# Generated by Django 5.0.1 on 2024-01-07 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('product_number', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('date_recieved', models.DateField()),
                ('description', models.CharField(max_length=40)),
                ('Price', models.BooleanField()),
                ('stocks', models.IntegerField()),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'ordering': ['date_recieved'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('staff_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(max_length=500)),
                ('contact', models.IntegerField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_entry'],
            },
        ),
    ]
