# Generated by Django 5.0.1 on 2024-01-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_staff_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
